Don't return policy description if there's not note attr
There's a few examples where the API response doesn't have `note` attribute causing:
NoMethodError
undefined method `gsub!' for nil (NoMethodError)

      note.gsub!(/https:\/\/(.+)/, "[https://\\1](https://\\1)")

          ^^^^^^

https://govuk.sentry.io/issues/6330840181/events/6958f220ade349e3940088ce42af1e50/

Examples:
- check-the-patents-journal
- check-national-insurance-record
- get-access-evisa