Fix `ContentRowPresenter` if `document_type.nil?`
`humanize(nil)` currently raises ``NoMethodError: undefined method `end_with?' for nil:NilClass`` due to a regression in Rails 7.0.6 (see rails/rails#48800)